### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by btvoidx** [onyx-lang/onyx-lsp#5]
I get this error when running `onyx package sync` / `onyx package build` on 96082f88895c60f8ec78e76bb0db570217bd45ee on windows 11. Please help.
```
(C:\Users\user\onyx\core\runtime\platform\onyx\platform.onyx:101,29) Unable to resolve symbol 'main'. Did you mean 'map'?
 101 |     #local MAIN_FUNCTION :: main.main
                                   ^~~~
(0,0) Failed to open file C:\Users\user\onyx\tools\onyx-pkg.onyx
(C:\Users\user\onyx\core\runtime\platform\onyx\platform.onyx:135,5) Expected this condition to be compile time known.
 135 |     #if (typeof MAIN_FUNCTION) == #type () -> void { // An error on this line means no 'main.main' was found in your program.
           ^
(C:\Users\user\onyx\core\runtime\platform\onyx\platform.onyx:100,5) Package 'main' not found in included source files.
 100 |     use main
           ^~~
```

**Comment by brendanfh** [comment]
This is related to another issue on the main Onyx repo, but I believe the root cause is that I forgot to ship the package manager script on the Windows build in this release. Here is the issue with the fix I proposed for this version of Onyx, https://github.com/onyx-lang/onyx/issues/51. So long as you have `git.exe` accessible in your command prompt, this should fix it for you.

**Comment by brendanfh** [comment]
Is Onyx in your system's path? I think this is because its trying to spawn `onyx.exe` to compile the LSP, but it isn't able to find it.

**Comment by btvoidx** [comment]
Yes, it is.

I did some quick debugging and added
```
    info_print("PATH", "'{}'.\n", os.env_vars());
```
to `onyx-pkg.onyx` on line 637, right after a call to `os.process_spawn`.

The output:
```
    Building  Compiling with build configuration 'default'.
FAILED TO CREATE PROCESS: 2
        PATH  '{  }'.
       Error  Failed to compile with build configuration 'default'.
```

Pretty much the same happened with `os.env("PATH")` - it was reported as `'NONE'`.

Could it be some wasm runtime issue?

**Comment by brendanfh** [comment]
This may be a silly question but its been a while since I was on Windows... Does line 636 need to be ```
p := os.process_spawn("onyx.exe", args);
```
In other words, does it need the `.exe` at the end?

**Comment by btvoidx** [comment]
This appears to make no difference.

**Comment by brendanfh** [comment]
Darn, that was just a hopeful guess. I will investigate this in a VM and get back to soon.

**Comment by btvoidx** [comment]
Any updates?

**Comment by brendanfh** [comment]
I pushed some updates into a nightly release on the main Onyx repository [here](https://github.com/onyx-lang/onyx/releases/nightly). These include some fixes for Windows related things, so you can install that version and try now. I'm not 100 percent confident it will work, but it should do better, I hope.
